version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - outline

  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - outline

  outline:
    image: outlinewiki/outline:latest
    ports:
      - "3000:3000"
    env_file:
      - .docker.env
    volumes:
      - outline_data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - outline
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:
  outline_data:

networks:
  outline:
    driver: bridge